### ISSUE TITLE
Problem generating the mongoDB template

### ISSUE THREAD

**Issue by ichigo-k** [ehoneahobed/create-express-boilerplate#4]
![image](https://github.com/ehoneahobed/create-express-boilerplate/assets/125087781/6a548874-86c9-4af8-af48-b2d793dcac1e)

I'm encountering an error while attempting to render the MongoDB template, and I suspect the issue might be stemming from the cli.js file. Would you mind taking a look at it to see if anything stands out?

**Comment by ehoneahobed** [comment]
It works fine at my end. I have also tried in an online sandbox and it worked fine.
![Screenshot 2024-04-11 112844](https://github.com/ehoneahobed/create-express-boilerplate/assets/27689532/f27cea34-d776-4fca-840c-56ff41adbc4c)

**Comment by ichigo-k** [comment]
Oh okay, then I will try it again , thanks.
